### ISSUE TITLE
Error installing HCMGIS on QGIS 3.0.0

### ISSUE THREAD

**Issue by ernbkr** [opengeoshub/HCMGIS#4]
Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'qgsfieldcombobox' 

Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 336, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\HCMGIS\hcmgis_dialogs.py", line 39, in 
    from hcmgis_lec_form import *
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms\hcmgis_lec_form.py", line 46, in 
    from qgsfieldcombobox import QgsFieldComboBox
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'qgsfieldcombobox'

Python version: 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] 
QGIS version: 3.0.0-Girona Girona, 001c80b0c3 

Python Path:
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.0\bin\python36.zip
C:\PROGRA~1\QGIS3~1.0\apps\Python36\DLLs
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib
C:\Program Files\QGIS 3.0\bin
C:\PROGRA~1\QGIS3~1.0\apps\Python36
C:\PROGRA~1\QGIS3~1.0\apps\Python36\lib\site-packages
C:/Users/Admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\Beeline/libs
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\mmqgis/forms
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms
C:\Users\Admin\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\HCMGIS/forms

**Comment by thangqd** [comment]
fixed already

**Comment by orkutmuratyilmaz** [comment]
It still exists on QGIS 3.16.0 too.

We get the error message which I paste below, on Pop!_OS (Ubuntu 20.04 derivative).

```
Couldn't load plugin 'HCMGIS' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'hcmgis_library' 
Traceback (most recent call last):
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 32, in 
    from .hcmgis_library import *
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_library.py", line 37, in 
    import processing
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/__init__.py", line 26, in 
    from processing.tools.general import *  # NOQA
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/tools/general.py", line 32, in 
    from processing.core.Processing import Processing
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/core/Processing.py", line 77, in 
    from processing.modeler.ModelerAlgorithmProvider import ModelerAlgorithmProvider  # NOQA
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/ModelerAlgorithmProvider.py", line 40, in 
    from processing.modeler.CreateNewModelAction import CreateNewModelAction
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/CreateNewModelAction.py", line 32, in 
    from processing.modeler.ModelerDialog import ModelerDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/modeler/ModelerDialog.py", line 56, in 
    from processing.script.ScriptEditorDialog import ScriptEditorDialog
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/script/ScriptEditorDialog.py", line 52, in 
    WIDGET, BASE = uic.loadUiType(
  File "/app/share/qgis/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
  File "/app/lib/python3.8/site-packages/PyQt5/uic/__init__.py", line 204, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 143, in 
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/app/share/qgis/python/plugins/processing/script/ScriptEdit.py", line 28, in 
    from qgis.gui import QgsCodeEditorPython
ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' (/app/share/qgis/python/qgis/gui/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/qgis/python/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/__init__.py", line 11, in classFactory
    from .hcmgis_menu import hcmgis_menu
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_menu.py", line 11, in 
    from .hcmgis_dialogs import *
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/HCMGIS/hcmgis_dialogs.py", line 34, in 
    from hcmgis_library import *
  File "/app/share/qgis/python/qgis/utils.py", line 792, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'hcmgis_library'


Python version: 3.8.6 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
QGIS version: 3.16.0-Hannover Hannover, 43b64b13 

Python Path:
/app/share/qgis/python
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
```
